cart/urls.py
from django.shortcuts import render
from django.urls import path
from cart import views

# Create your views here.
app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/', views.AddtoCart, name='AddtoCart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('remove_all/<int:product_id>/', views.remove_all, name='remove_all'),

]

ecommerce_app/urls.py
from django.urls import path
from ecommerce_app import views
app_name='ecommerce_app'
urlpatterns=[
    path('',views.AllProdCat,name='AllProdCat'),
    path('<slug:c_slug>/', views.AllProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>', views.ProDetail, name='prodCatdetail')

]

ecommerceproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from ecommerceproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce_app/',include('ecommerce_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from search_app import views
app_name='search_app'

urlpatterns = [
    path('',views.SearchQuery,name='SearchQuery'),
]

cart/models.py
from django.db import models
from ecommerce_app.models import Product
from django.core.exceptions import ObjectDoesNotExist

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id
class Cartitems(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='Cartitems'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

ecommerce_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecommerce_app:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price= models.DecimalField(max_digits=250,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
         return reverse('ecommerce_app:prodCatdetail',args=[self.category.slug,self.slug])

    class Meta:
            ordering = ('name',)
            verbose_name = 'product'
            verbose_name_plural = 'products'

    def __str__(self):
            return '{}'.format(self.name)

search_app/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from cart.models import Cart,Cartitems
from ecommerce_app.models import Product

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.session_create()
    return cart

def AddtoCart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = Cartitems.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Cartitems.DoesNotExist:
        cart_item = Cartitems.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=Cartitems.objects.filter(cart=cart,active=True)
        for item in cart_items:
            total += (item.product.price*item.quantity)
            counter += item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_items=Cartitems.objects.get(product=product,cart=cart)
    if cart_items.quantity > 1:
        cart_items.quantity -= 1
        cart_items.save()
    else:
        cart_items.delete()
    return redirect('cart:cart_detail')
def remove_all(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_items = Cartitems.objects.get(product=product, cart=cart)
    cart_items.delete()
    return redirect('cart:cart_detail')

ecommerce_app/views.py
from django.shortcuts import render,get_object_or_404
from ecommerce_app.models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
def AllProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list= Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(Paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})
def ProDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q
# Create your views here.
def SearchQuery(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return  render(request,'search.html',{'query':query,'products':products})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/fonts.googleapis.com/css2' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/e7a5f290cb.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
     <script src="{% static 'js/popper.min.js' %}" ></script>
     <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is Your ABC cart.Please proceed to review your items and place order
{% endblock %}
{% block title %}
Cart -ABC company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your ABC cart is Empty
        </h1>
        <br>
        <p class="text-center">
            <a href="{% url 'ecommerce_app:AllProdCat' %}">Continue Shopping</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your ABC Cart
        </h1>
         <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12  col-md-12 col-lg-6 text-center">
         <table class="table my_custom_table">
              <thead class="my_custom_thead">
               <tr>
                  <th colspan="5">
                      Your Items
                  </th>
               </tr>
               </thead>
             <tbody>
             {% for items in cart_items %}
             <tr>
                 <td>
                     <a href="items.product.get_absolute_url"><img src="{{items.product.image.url}}" alt=""  style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
                 </td>
                 <td class="text-left">
                     {{items.product.name}}
                     <br>
                     SKU:{{items.product.id}}
                     <br>
                      Price:${{items.product.price}}
                     <br>
                      QTY:{{items.quantity}} * ${{items.}}
                 </td>
                 <td>
                     ${{items.sub_total}}
                 </td>
                 {% if items.quantity < items.product.stock %}
                 <td>
                     <a href="{% url 'cart:AddtoCart'  items.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                     &nbsp;<a href="{% url 'cart:cart_remove' items.product.id %}" class="custom_a"><i class="fa fa-minus"></i></a>
                     &nbsp;<a href="{% url 'cart:remove_all' items.product.id %}" class="custom_icon"><i class="fa fa-trash"></i></a>

                 </td>
                 {% else %}
                 <td>
                     &nbsp;<a href="{% url 'cart:cart_remove' items.product.id %}" class="custom_a"><i class="fa fa-minus"></i></a>
                     &nbsp;<a href="{% url 'cart:remove_all' items.product.id %}" class="custom_icon"><i class="fa fa-trash"></i></a>
                 </td>
                 {% endif %}

             </tr>

             {% endfor %}
             </tbody>
         </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_head">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your cart items before you proceed to payment
                </td>
            </tr>
            <tr>
               <td class="text-left">
                 Your Total is : {{total}}
               </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ecommerce_app:AllProdCat' %}" class=" btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
     {{category.description|truncatewords:155}}
{% else %}
     Welcome to ABC store where you can buy different items..
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
     {{category.name}}- ABC store
{% else %}
      See our new collections-ABC store
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
<div class="row my-class-row">
      <div class="max-auto">
          <p><a href="{% url 'ecommerce_app:AllProdCat' %}">Our product Collections</a></p>
      </div>
</div>
</div>
{% endif %}
<div class="max-auto">
    {% if category %}
       <img  class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify" >{{category.description}}</p>
</div>
{% else %}

    <img class="my_image my_image_padding" src="{% static 'img/banner1.png' %}" alt="Our products" >

<div>
    <h1 class="text-center my_title">Our product collections</h1>
    <p class="text-center" >We have wide variety of clothings available.You have to select as much as your interest.For more details scroll the entire website.</p>
</div>
{% endif %}
<div class="container">
    <div class="row mx-auto ">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" ></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
<div class="mx-auto">
    {% if products.paginator.num_pages > 1 %}
    <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
    {% endif %}
</div>
</div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; ABC tech pvt Ltd.All rights Reserved</p>
</div>

templates/header.html
{%  load static %}
<header>
   <center>
            <a href="{% url 'ecommerce_app:AllProdCat' %}"><img src="{% static 'img/logo1.png' %}" alt="logimage" width="200" height="200">
    </center>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'ecommerce_app' in  request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecommerce_app:AllProdCat' %}">All products</a></li>
                      {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                      {% endfor %}
          </ul>
          {% if item_count > 0 %}
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}" ><i class="fa-solid fa-cart-shopping">({{item_count}})</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex"  action="{% url 'search_app:SearchQuery' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-brands fa-searchengin"></i></button>
      </form>
    </div>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {{product.description}}
{% endblock %}
{% block title %}
{% if category %}
     {{product.name}}- ABC store
{% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'ecommerce_app:AllProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">
            {{product.category}}</a>|{{product.name}}</p>

    </div>
    <div class="container">
    <br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt ="{{product.name}}">
        </div>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.desc}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:AddtoCart' product.id %}">Add to cart</a>
            {% endif %}
        </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  We have variety of stunning products available
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content%}
<div>
   <p class="text-center my_search_text">You have searched for:<b>{{query}}</b></p>
</div>
<div class="container">
    <div class="row mx-auto ">
        {% for product in products  %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" ></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>

            </div>
        </div>
      {% empty %}
      <div class="row mx_auto">
        <p class="text-center my_search_text">0 results found</p>
      </div>
        {% endfor %}
    </div>
</div>
{% endblock %}